version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    groups:
      hilt:
        patterns:
          - "com.google.dagger:*"
          - "androidx.hilt:*"
      kotlin:
        patterns:
          - "androidx.compose.compiler:compiler"
          - "org.jetbrains.kotlin*"