name: create-release

on:
  # TODO: remove
  push:
    branches:
      - release-workflow
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Build release
        run: ./gradlew bundleRelease

      - name: Download bundletool
        run: |
          # Source: https://github.com/actions/runner-images/issues/5751#issuecomment-1156623558
          json=$(curl -s https://api.github.com/repos/google/bundletool/releases/latest)
          downloadUrl=$(echo $json | jq -r ".assets | .[].browser_download_url")
          curl $downloadUrl -4 -sL -o "bundletool.jar"

      - name: Decrypt the keystore
        run: |
          gpg --quiet --batch --yes --decrypt \
            --passphrase="${{ secrets.RELEASE_KEYSTORE_GPG_PASSPHRASE }}" \
            --output ./keystore.jks \
            ./keystore.jks.gpg

      - name: Sign the release .aab
        run: |
          jarsigner -keystore ./keystore.jks \
          "./app/build/outputs/bundle/release/app-release.aab ${{ secrets.RELEASE_KEYSTORE_KEY_ALIAS }}" \
          -storepass "${{ secrets.RELEASE_KEYSTORE_STOREPASS }}" \
          -keypass "${{ secrets.RELEASE_KEYSTORE_KEYPASS }}"

      - name: Extract version name
        id: extract
        run: |
          version_name=$(bundletool dump manifest \
            --bundle ./app/build/outputs/bundle/release/app-release.aab \
            --xpath /manifest/@android:versionName)
          echo "version_name=$version_name" >> $GITHUB_OUTPUT
          
          version_code=$(bundletool dump manifest \
            --bundle ./app/build/outputs/bundle/release/app-release.aab \
            --xpath /manifest/@android:versionCode)
          echo "version_code=$version_code" >> $GITHUB_OUTPUT

      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create Tag
        run: |
          git tag ${{ steps.extract.outputs.version_code }}
          git push origin ${{ steps.extract.outputs.version_code }}

      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./app/build/outputs/bundle/release/app-release.aab"
          artifactErrorsFailBuild: true
          generateReleaseNotes: true
          tag: ${{ steps.extract.outputs.version_code }}
          name: "${{ steps.extract.outputs.version_name }} ${{ steps.extract.outputs.version_code }}"

      # TODO: upload release
#
#      - name: Upload app
#        run: |
#          uses: r0adkll/upload-google-play@v1
#          with:
#            serviceAccountJsonPlainText: ${{ SERVICE_ACCOUNT_JSON }}
#            packageName: com.example.MyApp
#            releaseFiles: app/build/outputs/bundle/release/app-release.aab
#            track: production
#            status: inProgress
#            inAppUpdatePriority: 2
#            userFraction: 0.33
#            whatsNewDirectory: distribution/whatsnew
#            mappingFile: app/build/outputs/mapping/release/mapping.txt
#            debugSymbols: app/intermediates/merged_native_libs/release/out/lib
#
