name: on-pull-request

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Run tests
        run: ./gradlew testDebugUnitTest

      - name: Tests results
        if: always()
        run:
          cat app/build/reports/tests/testDebugUnitTest/index.html >> $GITHUB_STEP_SUMMARY

      - name: Run Gradle tests
        run: ./gradlew :build-logic:plugins:test

      - name: Gradle test results
        if: always()
        run:
          cat build-logic/plugins/build/reports/tests/test/index.html >> $GITHUB_STEP_SUMMARY

      - name: Build release to ensure it is working
        run: ./gradlew bundleRelease

      - name: Automerge
        if: github.event.pull_request.user.login != 'dependabot[bot]'
        run: gh pr merge --delete-branch --merge --auto ${{ github.head_ref }}
        env:
          GH_TOKEN: ${{ github.token }}
